# Generated by Django 5.2.1 on 2025-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='miles',
            field=models.CharField(default='25 mi', max_length=50),
            preserve_default=False,
        ),
    ]
