# Generated by Django 5.2.1 on 2025-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_car_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='silver', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(default='4 doors', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(default='2024', max_length=50),
            preserve_default=False,
        ),
    ]
