# Generated by Django 5.2.1 on 2025-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_city_order_city_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_key',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
